FILTER_OPTIONS = {
    "genres": [
        "Action",
        "Adult",
        "Adventure",
        "Boys Love",
        "Comedy",
        "Drama",
        "Ecchi",
        "Fanfiction",
        "Fantasy",
        "Gender Bender",
        "Girls Love",
        "Harem",
        "Historical",
        "Horror",
        "Isekai",
        "Josei",
        "LitRPG",
        "Martial Arts",
        "Mature",
        "Mecha",
        "Mystery",
        "Psychological",
        "Romance",
        "School Life",
        "Sci-fi",
        "Seinen",
        "Slice of Life",
        "Smut",
        "Sports",
        "Supernatural",
        "Tragedy"
        ],
    "tags": [ 
        "Abandoned Children",
        "Ability Steal",
        "Absent Parents"
        "Abusive Characters",
        "Academy",
        "Accelerated Growth",
        "Acting",
        "Adopted Children",
        "Adopted Protagonist",
        "Adultery",
        "Adventurers",
        "Affair",
        "Age Progression",
        "Age Regression",
        "Aggressive Characters",
        "Alchemy",
        "Aliens",
        "All-Girls School",
        "Alternate World",
        "Amnesia",
        "Amusement Park",
        "Ancient China",
        "Ancient Times",
        "Androgynous Characters",
        "Androids",
        "Angels",
        "Animal Characteristics",
        "Animal Rearing",
        "Anti-Magic",
        "Anti-social Protagonist",
        "Antihero Protagonist",
        "Antique Shop",
        "Apartment Life",
        "Apathetic Protagonist",
        "Apocalypse",
        "Appearance Changes",
        "Appearance Different from Actual Age",
        "Archery",
        "Aristocracy",
        "Arms Dealers",
        "Army",
        "Army Building",
        "Arranged Marriage",
        "Arrogant Characters",
        "Artifact Crafting",
        "Artifacts",
        "Artificial Intelligence",
        "Artists",
        "Assassins",
        "Astrologers",
        "Autism",
        "Automatons",
        "Average-looking Protagonist",
        "Awkward Protagonist",
        "BDSM",
        "Bands",
        "Based on a Movie",
        "Based on a Song",
        "Based on a Video Game",
        "Based on a Visual Novel",
        "Based on an Anime",
        "Battle Academy",
        "Battle Competition",
        "Beast Companions",
        "Beastkin",
        "Beasts",
        "Beautiful Couple",
        "Beautiful Female Lead",
        "Betrayal",
        "Bickering Couple",
        "Biochip",
        "Biography",
        "Bisexual Protagonist",
        "Black Belly",
        "Blackmail",
        "Blacksmith",
        "Blind Dates",
        "Blind Protagonist",
        "Blood Manipulation",
        "Bloodlines",
        "Body Swap",
        "Body Tempering",
        "Body-double",
        "Bodyguards",
        "Books",
        "Bookworm",
        "Boss-Subordinate Relationship",
        "Boy's Love Subplot",
        "Brainwashing",
        "Broken Engagement",
        "Brother Complex",
        "Brotherhood",
        "Buddhism",
        "Bullying",
        "Business Management",
        "Businessmen",
        "Butlers",
        "Calm Protagonist",
        "Cannibalism",
        "Card Games",
        "Carefree Protagonist",
        "Caring Protagonist",
        "Cautious Protagonist",
        "Celebrities",
        "Character Growth",
        "Charismatic Protagonist",
        "Charming Protagonist",
        "Chat Rooms",
        "Cheating",
        "Cheats",
        "Chefs",
        "Child Abuse",
        "Child Protagonist",
        "Childcare",
        "Childhood Friends",
        "Childhood Love",
        "Childhood Promise",
        "Childish Protagonist",
        "Chuunibyou",
        "Clan Building",
        "Classic",
        "Clever Protagonist",
        "Clingy Lover",
        "Clones",
        "Clubs",
        "Clumsy Love Interests",
        "Co-Workers",
        "Cohabitation",
        "Cold Love Interests",
        "Cold Protagonist",
        "Collection of Short Stories",
        "College/University",
        "Coma",
        "Comedic Undertone",
        "Coming of Age",
        "Complex Family Relationships",
        "Conditional Power",
        "Confident Protagonist",
        "Confinement",
        "Conflicting Loyalties",
        "Conspiracies",
        "Contracts",
        "Cooking",
        "Corruption",
        "Cosmic Wars",
        "Cosplay",
        "Couple Growth",
        "Court Official",
        "Cousins",
        "Cowardly Protagonist",
        "Crafting",
        "Crazy Protagonist",
        "Crime",
        "Criminals",
        "Cross-dressing",
        "Crossover",
        "Cruel Characters",
        "Cryostasis",
        "Cultivation",
        "Cunning Protagonist",
        "Curious Protagonist",
        "Curses",
        "Cute Children",
        "Cute Protagonist",
        "Cute Story",
        "Cyberpunk",
        "Dancers",
        "Dao Companion",
        "Dao Comprehension",
        "Daoism",
        "Dark",
        "Dead Protagonist",
        "Death",
        "Death of Loved Ones",
        "Debts",
        "Delinquents",
        "Delusions",
        "Demi-Humans",
        "Demon Lord",
        "Demonic Cultivation Technique",
        "Demons",
        "Dense Protagonist",
        "Depictions of Cruelty",
        "Depression",
        "Destiny",
        "Detectives",
        "Determined Protagonist",
        "Devoted Love Interests",
        "Different Social Status",
        "Disabilities",
        "Discrimination",
        "Disfigurement",
        "Dishonest Protagonist",
        "Distrustful Protagonist",
        "Divination",
        "Divine Protection",
        "Divorce",
        "Doctors",
        "Dolls/Puppets",
        "Domestic Affairs",
        "Doting Love Interests",
        "Doting Older Siblings",
        "Doting Parents",
        "Dragon Riders",
        "Dragon Slayers",
        "Dragons",
        "Dreams",
        "Drugs",
        "Druids",
        "Dungeon Master",
        "Dungeons",
        "Dwarfs",
        "Dystopia",
        "Early Romance",
        "Earth Invasion",
        "Easy Going Life",
        "Economics",
        "Editors",
        "Eidetic Memory",
        "Elderly Protagonist",
        "Elemental Magic",
        "Elves",
        "Emotionally Weak Protagonist",
        "Empires",
        "Enemies Become Allies",
        "Enemies Become Lovers",
        "Engagement",
        "Engineer",
        "Enlightenment",
        "Episodic",
        "Eunuch",
        "European Ambience",
        "Evil Gods",
        "Evil Organizations",
        "Evil Protagonist",
        "Evil Religions",
        "Evolution",
        "Exhibitionism",
        "Exorcism",
        "Eye Powers",
        "Fairies",
        "Fallen Angels",
        "Fallen Nobility",
        "Familial Love",
        "Familiars",
        "Family",
        "Family Business",
        "Family Conflict",
        "Famous Parents",
        "Famous Protagonist",
        "Fanaticism",
        "Fantasy Creatures",
        "Fantasy World",
        "Farming",
        "Fast Cultivation",
        "Fast Learner",
        "Fat Protagonist",
        "Fat to Fit",
        "Fated Lovers",
        "Fearless Protagonist",
        "Female Master",
        "Female Protagonist",
        "Female to Male",
        "Feng Shui",
        "Firearms",
        "First Love",
        "First-time Intercourse",
        "Flashbacks",
        "Fleet Battles",
        "Folklore",
        "Forced Living Arrangements",
        "Forced Marriage",
        "Forced into a Relationship",
        "Forgetful Protagonist",
        "Former Hero",
        "Fourth Wall",
        "Fox Spirits",
        "Friends Become Enemies",
        "Friendship",
        "Fujoshi",
        "Futanari",
        "Futuristic Setting",
        "Galge",
        "Gambling",
        "Game Elements",
        "Game Ranking System",
        "Gamers",
        "Gangs",
        "Gate to Another World",
        "Genderless Protagonist",
        "Generals",
        "Genetic Modifications",
        "Genies",
        "Genius Protagonist",
        "Ghosts",
        "Girl's Love Subplot",
        "Gladiators",
        "Glasses-wearing Love Interests",
        "Glasses-wearing Protagonist",
        "Goblins",
        "God Protagonist",
        "God-human Relationship",
        "Goddesses",
        "Godly Powers",
        "Gods",
        "Golems",
        "Gore",
        "Grave Keepers",
        "Grinding",
        "Guardian Relationship",
        "Guilds",
        "Gunfighters",
        "Hackers",
        "Half-human Protagonist",
        "Handjob",
        "Handsome Male Lead",
        "Hard-Working Protagonist",
        "Harem-seeking Protagonist",
        "Harsh Training",
        "Hated Protagonist",
        "Healers",
        "Healing",
        "Heartwarming",
        "Heaven",
        "Heavenly Tribulation",
        "Hell",
        "Helpful Protagonist",
        "Herbalist",
        "Heroes",
        "Heterochromia",
        "Hidden Abilities",
        "Hiding True Abilities",
        "Hiding True Identity",
        "Hikikomori",
        "Homunculus",
        "Honest Protagonist",
        "Hospital",
        "Hot-blooded Protagonist",
        "Human Experimentation",
        "Human Weapon",
        "Human-Nonhuman Relationship",
        "Humanoid Protagonist",
        "Hunters",
        "Hypnotism",
        "Identity Crisis",
        "Imaginary Friend",
        "Immortals",
        "Imperial Harem",
        "Incest",
        "Incubus",
        "Indecisive Protagonist",
        "Industrialization",
        "Inferiority Complex",
        "Inheritance",
        "Inscriptions",
        "Insects",
        "Interconnected Storylines",
        "Interdimensional Travel",
        "Introverted Protagonist",
        "Investigations",
        "Invisibility",
        "Jack of All Trades",
        "Jealousy",
        "Jiangshi",
        "Jobless Class",
        "Kidnappings",
        "Kind Love Interests",
        "Kingdom Building",
        "Kingdoms",
        "Knights",
        "Kuudere",
        "Lack of Common Sense",
        "Language Barrier",
        "Late Romance",
        "Lawyers",
        "Lazy Protagonist",
        "Leadership",
        "Legends",
        "Level System",
        "Library",
        "Limited Lifespan",
        "Living Abroad",
        "Living Alone",
        "Loli",
        "Loneliness",
        "Loner Protagonist",
        "Long Separations",
        "Long-distance Relationship",
        "Lost Civilizations",
        "Lottery",
        "Love Interest Falls in Love First",
        "Love Rivals",
        "Love Triangles",
        "Love at First Sight",
        "Lovers Reunited",
        "Low-key Protagonist",
        "Loyal Subordinates",
        "Lucky Protagonist",
        "MMORPG",
        "Magic",
        "Magic Beasts",
        "Magic Formations",
        "Magical Girls",
        "Magical Space",
        "Magical Technology",
        "Maids",
        "Male Protagonist",
        "Male Yandere",
        "Male to Female",
        "Management",
        "Mangaka",
        "Manipulative Characters",
        "Manly Gay Couple",
        "Marriage",
        "Marriage of Convenience",
        "Martial Spirits",
        "Masochistic Characters",
        "Master-Disciple Relationship",
        "Master-Servant Relationship",
        "Masturbation",
        "Matriarchy",
        "Mature Protagonist",
        "Medical Knowledge",
        "Medieval",
        "Mercenaries",
        "Merchants",
        "Military",
        "Mind Break",
        "Mind Control",
        "Misandry",
        "Mismatched Couple",
        "Misunderstandings",
        "Mob Protagonist",
        "Models",
        "Modern Day",
        "Modern Fantasy",
        "Modern Knowledge",
        "Modern Time",
        "Money Grubber",
        "Monster Girls",
        "Monster Society",
        "Monster Tamer",
        "Monsters",
        "Movies",
        "Mpreg",
        "Multiple Identities",
        "Multiple POV",
        "Multiple Personalities",
        "Multiple Protagonists",
        "Multiple Realms",
        "Multiple Reincarnated Individuals",
        "Multiple Timelines",
        "Multiple Transported Individuals",
        "Murders",
        "Music",
        "Mutated Creatures",
        "Mutations",
        "Mute Character",
        "Mysterious Family Background",
        "Mysterious Illness",
        "Mysterious Past",
        "Mystery Solving",
        "Mythical Beasts",
        "Mythology",
        "Naive Protagonist",
        "Narcissistic Protagonist",
        "Nationalism",
        "Near-Death Experience",
        "Necromancer",
        "Neet",
        "Netorare",
        "Netorase",
        "Netori",
        "Nightmares",
        "Ninjas",
        "Nobles",
        "Non-human Protagonist",
        "Non-humanoid Protagonist",
        "Non-linear Storytelling",
        "Nudity",
        "Nurses",
        "Obsessive Love",
        "Office Romance",
        "Older Love Interests",
        "Omegaverse",
        "Oneshot",
        "Online Romance",
        "Onmyouji",
        "Orcs",
        "Organized Crime",
        "Orphans",
        "Otaku",
        "Otome Game",
        "Outcasts",
        "Outdoor Intercourse",
        "Outer Space",
        "Overpowered Protagonist",
        "Overprotective Siblings",
        "Pacifist Protagonist",
        "Paizuri",
        "Pansexual Protagonist",
        "Parallel Worlds",
        "Parasites",
        "Parent Complex",
        "Parody",
        "Part-Time Job",
        "Past Plays a Big Role",
        "Past Trauma",
        "Persistent Love Interests",
        "Personality Changes",
        "Perverted Protagonist",
        "Pets",
        "Pharmacist",
        "Philosophical",
        "Phobias",
        "Phoenixes",
        "Photography",
        "Pill Based Cultivation",
        "Pill Concocting",
        "Pilots",
        "Pirates",
        "Playboys",
        "Playful Protagonist",
        "Poetry",
        "Poisons",
        "Police",
        "Polite Protagonist",
        "Politics",
        "Polyandry",
        "Polygamy",
        "Poor Protagonist",
        "Poor to Rich",
        "Popular Love Interests",
        "Possession",
        "Possessive Characters",
        "Post-apocalyptic",
        "Power Couple",
        "Power Struggle",
        "Pragmatic Protagonist",
        "Precognition",
        "Pregnancy",
        "Pretend Lovers",
        "Previous Life Talent",
        "Priestesses",
        "Priests",
        "Prison",
        "Proactive Protagonist",
        "Programmer",
        "Prophecies",
        "Prostitutes",
        "Protagonist Falls in Love First",
        "Protagonist Loyal to Love Interest",
        "Protagonist Strong from the Start",
        "Protagonist with Multiple Bodies",
        "Psychic Powers",
        "Psychopaths",
        "Puppeteers",
        "Quiet Characters",
        "Quirky Characters",
        "R-15",
        "R-18",
        "RPG",
        "Race Change",
        "Racism",
        "Rape",
        "Rebellion",
        "Reincarnated as a Monster",
        "Reincarnated as an Object",
        "Reincarnated into Another World",
        "Reincarnated into a Game World",
        "Reincarnation",
        "Religions",
        "Reluctant Protagonist",
        "Reporters",
        "Restaurant",
        "Resurrection",
        "Returning from Another World",
        "Revenge",
        "Reverse Harem",
        "Reverse Rape",
        "Rich to Poor",
        "Righteous Protagonist",
        "Rivalry",
        "Romantic Subplot",
        "Roommates",
        "Royalty",
        "Ruthless Protagonist",
        "Sadistic Characters",
        "Saints",
        "Salaryman",
        "Samurai",
        "Satire",
        "Saving the World",
        "Scheming",
        "Schizophrenia",
        "Scientists",
        "Sculptors",
        "Sealed Power",
        "Second Chance",
        "Secret Crush",
        "Secret Identity",
        "Secret Organizations",
        "Secret Relationship",
        "Secretive Protagonist",
        "Secrets",
        "Sect Development",
        "Seduction",
        "Seeing Things Other Humans Can't",
        "Selfish Protagonist",
        "Selfless Protagonist",
        "Seme Protagonist",
        "Senpai-Kouhai Relationship",
        "Sentient Objects",
        "Sentimental Protagonist",
        "Serial Killers",
        "Servants",
        "Seven Deadly Sins",
        "Seven Virtues",
        "Sex Friends",
        "Sexual Abuse",
        "Sexual Cultivation Technique",
        "Shameless Protagonist",
        "Shapeshifters",
        "Sharing A Body",
        "Sharp-tongued Characters",
        "Shield User",
        "Shikigami",
        "Short Story",
        "Shota",
        "Showbiz",
        "Shy Characters",
        "Sibling Rivalry",
        "Siblings",
        "Siblings Care",
        "Siblings Not Related by Blood",
        "Sickly Characters",
        "Sign Language",
        "Singers",
        "Single Parent",
        "Sister Complex",
        "Skill Assimilation",
        "Skill Books",
        "Skill Creation",
        "Slave Harem",
        "Slave Protagonist",
        "Slaves",
        "Sleeping",
        "Slow Growth at Start",
        "Slow Romance",
        "Smart Couple",
        "Social Outcasts",
        "Soldiers",
        "Soul Power",
        "Souls",
        "Spatial Manipulation",
        "Spear Wielder",
        "Special Abilities",
        "Special Forces",
        "Spies",
        "Spirit Advisor",
        "Spirit Users",
        "Spirits",
        "Stalkers",
        "Stockholm Syndrome",
        "Stoic Characters",
        "Store Owner",
        "Straight Seme",
        "Straight Uke",
        "Strategic Battles",
        "Strategist",
        "Strength-based Social Hierarchy",
        "Strong Love Interests",
        "Strong to Stronger",
        "Stubborn Protagonist",
        "Student Council",
        "Student-Teacher Relationship",
        "Subtle Romance",
        "Succubus",
        "Sudden Strength Gain",
        "Sudden Wealth",
        "Suicides",
        "Summoned Hero",
        "Summoning Magic",
        "Survival",
        "Survival Game",
        "Sword And Magic",
        "Sword Wielder",
        "System Administrator",
        "Teachers",
        "Teamwork",
        "Technological Gap",
        "Tentacles",
        "Terminal Illness",
        "Terrorists",
        "Thieves",
        "Threesome",
        "Thriller",
        "Time Loop",
        "Time Manipulation",
        "Time Paradox",
        "Time Skip",
        "Time Travel",
        "Timid Protagonist",
        "Tomboyish Female Lead",
        "Torture",
        "Toys",
        "Tragic Past",
        "Transformation Ability",
        "Transgender",
        "Transmigration",
        "Transplanted Memories",
        "Transported Modern Structure",
        "Transported into Another World",
        "Transported into a Game World",
        "Trap",
        "Tribal Society",
        "Trickster",
        "Trolls",
        "Tsundere",
        "Twins",
        "Twisted Personality",
        "Ugly Protagonist",
        "Ugly to Beautiful",
        "Unconditional Love",
        "Underestimated Protagonist",
        "Unique Cultivation Technique",
        "Unique Weapon User",
        "Unique Weapons",
        "Unlucky Protagonist",
        "Unreliable Narrator",
        "Unrequited Love",
        "Valkyries",
        "Vampires",
        "Villainess Noble Girls",
        "Virtual Reality",
        "Vocaloid",
        "Voice Actors",
        "Voyeurism",
        "Waiters",
        "War Records",
        "Wars",
        "Weak Protagonist",
        "Weak to Strong",
        "Wealthy Characters",
        "Werebeasts",
        "Wishes",
        "Witches",
        "Wizards",
        "World Hopping",
        "World Invasion",
        "World Travel",
        "World Tree",
        "Writers",
        "Wuxia",
        "Xianxia",
        "Xuanhuan",
        "Yandere",
        "Youkai",
        "Younger Brothers",
        "Younger Love Interests",
        "Younger Sisters",
        "Zombies",
        "e-Sports"
    ]
}

NOVEL_SUGGESTIONS = [
    "https://www.scribblehub.com/series/413997/the-young-master-in-the-shadows/",
    "https://www.scribblehub.com/series/117137/the-runesmith/",
    "https://www.scribblehub.com/series/624250/stuck-as-a-villain/",
    "https://www.scribblehub.com/series/10700/tree-of-aeons-an-isekai-story/",
    "https://www.scribblehub.com/series/10442/world-keeper/",
    "https://www.scribblehub.com/series/676682/a-gamer-adventure/",
    "https://www.scribblehub.com/series/114946/a-clich-multiverse-story/"
]

#TODO: Pick a random choice from user index instead.
USER_ID_SUGGESTIONS = [
    'https://www.scribblehub.com/profile/17062/unknownnovelist/', 
    '17062',
    'https://www.scribblehub.com/profile/17064/lufia/',
    '17064',
    '1706',
]

NOVEL_LABEL = 'ScribbleHub Novel ID or URL'

NOVEL_INPUT_HELP = "Input the ScribbleHub Novel ID or URL of the Novel you want to find are similar"

USER_INPUT_HELP = "Input your ScribbleHub User ID or  URL to get recomendations for the novels that you've added to your reading list"

END_MESSAGE = [
    "Did you like the recommendations? ◕ ◡ ◕",
    "There's no more! (╯°□°)╯︵ ┻━┻",
    "Check out the Top 100! (•̀ᴗ•́)و"
]

ERROR_MESSAGE = [
    "People like you are why we can't have nice things. ☜(ಠ_ಠ☜)",
    "Stop doing that!",
    "I told you. It doesn't work like that. (´Д｀)",
    "What are you trying to do? Baka! (>人<)",
    "I knew you were a rebel as soon as you came here. (ಠ_ಠ)",
    "... 눈_눈",
    "Even if you keep trying, nothing's gonna change. You know that, right?! (¬_¬)",
    "“Insanity is doing the same thing over and over and expecting different results.” (－‸ლ)",
    "UX and programming is about designing a system for idiots in mind. You should expect people to use it in ways you can't even imagine. And then take that into accout when shit goes down the drain. Unfortunately, you were one of them. (*￣m￣)",
    "What did you think was going to happen? o(-`д´- ｡)",
    "(╯°□°)╯︵ ┻━┻",
    "(´Д｀)",
]

USER_PARSE_ERROR = [
    "Did you enter a correct ID? It only accepts a ScribbleHub user ID or URL."
]

NOVEL_PARSE_ERROR = [
    "That might look like a valid novel ID where you're come from. But not here!"
]

UNKNOWN_USER_ERROR = [
    "It doesn't look like we have crawled your username. Why? Check the FAQ & About page."
]

UNKNOWN_NOVEL_ERROR = [
    "It doesn't look like we crawled that novel. Why? Check the FAQ & About page."
]

ERROR = [
    "Something weird is going on! It looks like you entered a correct ID or URL, but things went awry. Can you contact me and tell me how you did it?"
]

STATISTICS = ["The ScribbleHub Scoop",
                "The Novel Nook",
                "The Writer's Window",
                "The Page of Numbers",
                "The Author's Assistant", 
                "The Statistician's Den", 
                "The Data Delight",
                "The Number Nerve Center",
                "The Graph Garden",
                "The Tale Teller's Treasury"
                ]

ABOUT_URL = None

GET_HELP_URL = None

REPORT = 'mailto:unkown.novelist@gmail.com'

from enum import Enum
class Pages(Enum):
    Main = {'title': 'Recommend Me Stuff :mag:',
            'icon': ":mag:",
            'page_name': 'ScribbleHub Explorer - Recommend Me Stuff',
            'description': """
            Welcome to the recommendation section of ScribbleHub Explorer, where you don't need to be a ScribbleHub user to find your next favorite novel.  
            To get started, just enter the URL or ID for a novel that you love.  
            The recommendation engine uses various "features" to match similarities between your chosen novel and our recommendations. 
            These features include the synopsis, genre, tags, fandom, weighted rating, number of readers, favorites, chapters, and views. If you'd like to learn more about how this engine works and how it differs from the "similar novels" option on the other page, you can visit the FAQ & About section.  
            In the mean time, you can sit back, relax, and let us do the work to find your next literary obsession.""",
            }
   
    Page_1 = {'title': "Make It Personal :hocho:",
              'icon': ":hocho:",
              'page_name': 'ScribbleHub Explorer - Make It Personal',
              'description': """
              You want to it to get up close and personal, eh? Well, here you can get personalized novel recommendations with a User-Item-based Implicit Collaborative Filtering Recommendation System (what a mouthful). Enter your ScribbleHub user ID or URL in the sidebar to the left and see what other avid readers like you have added to their reading list. The AI will match you with novels that you're bound to love based on your reading habits.  
              Don't have a ScribbleHub user ID yet? No problem. The system also suggests similar novels based on a single novel of your choice. Just type in the URL on the second tab below and get a list of handpicked novels that are bound to please.  
              Ready to dive in? Make sure you have at least 5 novels on your reading list for the best results!""",
              }
    
    Page_2 = {'title': "Unknown Novelist's Top 100 :fire:",
              'icon': ':fire:',
              'page_name': "ScribbleHub Explorer - UN's Top 100",
              'description': """
              Step right up for the ultimate reading experience! Presenting my personally curated, hand-picked, mindblowing Top 100 list of the best novels on ScribbleHub!  
              Using a handcrafted algorithm (totally not "stole-ahem" borrowed from a certain web-based movie database), I've calculated the Top 100 novels that you can find on ScribbleHub.  
              Want to know what makes this rating different from the normal rating on ScribbleHub? Head over to the FAQ & About section for that answer. Enjoy! """,
              }
    
    import random
    Page_3 = {'title': f'Statistics aka. "{random.choice(STATISTICS)}" :bar_chart:',
              'icon': ':bar_chart:',
              'page_name': "ScribbleHub Explorer - The Graph Garden",
              'description': """
              Get the inside scoop on ScribbleHub with this statistics page! Discover how many novels have been published, the hottest genres and tags, and which ones have the most readers, views, reviews and more.  
              Want to know the average word count or the number of chapters published? You'll find all the answers here. Don't miss out on the juicy details!  
              You're an author? Looking to get the most readers for your novel on ScribbleHub? Worry not! You've come to the right place. Here you can find out which genres and tags are the most popular among readers! You can see the latest trends and what's hot in the world of online writing, helping you to make informed decisions on how to get your novel noticed. Whether you're just starting out or you're a seasoned author, this page is a valuable tool that can help you reach more readers and grow your audience.""",
              }
    
    Page_4 = {'title': "",
              'icon': ':question:',
              'page_name': 'ScribbleHub Explorer - FAQ & About',
              'description': '',
              }
    
BUILD = "RELEASE" #TEST